### PR TITLE
Create settings layout

### PR DESCRIPTION
**Pull request by mattrrubino**
Adds the UI for the main settings view

Possible future improvements:
- Open color picker in a new view
- Use a section list for the main component
- Change the carrot to an image/icon

### CODE REVIEW

**Comment by emilkovacev** [comment]
So in testing it out, the dropdowns make using the elements a bit more difficult. I'm not sure why this happens, but adjusting color seems to also toggle scrolling, which is making setting values a bit difficult. I think we should work to fix the scrolling issue and move the dropdown into a new view before we merge.

**Comment by emilkovacev** [comment]
The color selection tool is perfect for being able to adjust those settings 👍

**Comment by mattrrubino** [comment]
I moved the color selector to a new view, which resolved the scrolling issue as well. However, I noticed some unusual behavior with the color picker on iOS that I am unable to fix (it seems to be a problem with the package itself). I am currently looking for alternatives and will make another PR once I find one that works.

**Comment by mattrrubino** [comment]
I switched the color wheel out for a color palette and put it on a new view. Here is what the color selection screen looks like now:

palette

Should I add a new commit?

**Comment by emilkovacev** [comment]
Looks good, go for it!

**Comment by emilkovacev** [comment]
I tested the functionality and it looks like it works perfectly. You should be ready to start writing the functionality to change the style appropriately. I can merge this into main for others who want to work on it, or wait for you to finish other functionality, what do you think is better?

**Comment by mattrrubino** [comment]
I think this would be a good time to merge the changes into main. I just implemented a persistent storage system, which will be useful in creating the functionality of other settings.

**Comment by emilkovacev** [comment]
I'll test the changes again tonight and merge them, and keep an eye out for other pull requests for storage

**Comment by emilkovacev** [comment]
is there any way to test the persistent storage system? You can either implement tests to see the storage works or wait to complete the colors being stored, what do you think?

**Comment by mattrrubino** [comment]
I believe the persistent storage system is working because when I select colors in the palette and exit the app, the same colors are selected the next time I open it. I will start working on styling the app to make sure everything is working properly.

**Review by emilkovacev — APPROVED** [review]

**Pull request merged**
