### PR TITLE
Add font scaling

### PR DESCRIPTION
**Pull request by mattrrubino**

### CODE REVIEW

**Comment by emilkovacev** [comment]
Should the font scale change the size of the "category" font? Also, should we consider changing the sizes of icons too? Just some considerations I had when testing, I don't have a strict opinion on these.

**Comment by mattrrubino** [comment]
For "category" font, are you referring to the text in the navigation header? If so, I believe it would make sense to scale this since it is important for users to see this detail. Same thing goes for the navigation icons.

**Comment by emilkovacev** [comment]
I agree 100%. From my testing, it didn't seem to scale either, but it shouldn't be too difficult a fix. If you'd like to make the change, feel free to move ahead with it, otherwise, I can merge to a new branch and make another PR. Either way, once the fix is made I'll merge it with main!

**Comment by emilkovacev** [comment]
Apologies for not getting to this sooner. I noticed a couple of things with the icons when scaled larger. 

1. The icons seem to be slightly more pixelated. I'm not sure if this is just my device or a broader issue with the SVG icons.
2. The icons also seem to clip into the edges of the menu bar, I'm guessing because the height of the menu bar is static (and maybe should be dynamic?). 

My suggestions would be to either cut out some of the larger scaling options or to make the menu itself scale properly. The first method would definitely be an easier fix, but what do you think is best?

**Comment by mattrrubino** [comment]
I think scaling the header would be best, but I cannot find a way to change the header height on iOS (aside from building a custom header from scratch). I'll remove the larger scaling options for now and revisit this again later if we decide that the larger options are needed.

**Comment by emilkovacev** [comment]
Sounds good, now that that's fixed, the PR is ready to be merged

**Review by emilkovacev — APPROVED** [review]

**Pull request merged**
